events { worker_connections 1024; }
http {
  server {
    listen 80;
    server_name attendify.tech www.attendify.tech;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / {
      proxy_pass http://ams_frontend:80;
      proxy_set_header Host $host;
    }
  }
  server {
    listen 80;
    server_name api.attendify.tech;
    client_max_body_size 20M;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location /ws/ {
      proxy_pass http://ams_backend:8000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 86400;
    }
    location / {
      proxy_pass http://ams_backend:8000;
      proxy_set_header Host $host;
    }
  }
}
